language: node_js
sudo: required
node_js:
  - "12"
  - "14"
  - "15"
env:
  - NODE_ENV=travis
cache:
  npm
script: npm run lint && npm test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/249daf9851ea4776f34e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
