version: '3.4'

services:
  express-starter-kit:
    container_name: express-starter-kit
    build: .
    working_dir: /usr/src/app
    command: sh -c "npm start"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/:/usr/src/app/src
      # - ./swagger.yaml:/usr/src/app/swagger.yaml
      - ./test/:/usr/src/app/test
      - ./config/:/usr/src/app/config
    ports:
      - 3000:3000
